name: ExampleCoordinateOffsetAPIPlugin
version: 0.0.1
main: com.jtprince.coordinateoffset.example.ExampleCoordinateOffsetAPIPlugin
api-version: "1.21"
authors: [ joshuaprince ]
website: https://github.com/joshuaprince/CoordinateOffset
description: Example Coordinate Offset API Plugin
depend: [ CoordinateOffset ]
